//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETSANPHAM
    {
        public int ID { get; set; }
        public string MACHITIETSANPHAM { get; set; }
        public string MALOAI { get; set; }
        public string TENSANPHAM { get; set; }
        public Nullable<double> GIA { get; set; }
        public string MAUSAC { get; set; }
        public string MOTASANPHAM { get; set; }
        public string HINHANH { get; set; }
        public string MANCC { get; set; }
    }
}
