//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIA
    {
        public int ID { get; set; }
        public string MADANHGIA { get; set; }
        public string MACHITIETSANPHAM { get; set; }
        public string MAKHACHHANG { get; set; }
        public Nullable<double> DIEMDANHGIA { get; set; }
        public string BINHLUAN { get; set; }
    }
}
