//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHTOANDONMUA
    {
        public int ID { get; set; }
        public string MATHANHTOANDONMUA { get; set; }
        public string MADONMUA { get; set; }
        public Nullable<System.DateTime> NGAYTHANHTOAN { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
    }
}
